---
arch_base_packages:
  - git
  - stow
  - curl
  - wget
  - neovim
  - tmux
  - zsh
  - base-devel
  - openssh
  - python
  - starship
  - fastfetch
  - ripgrep
  - fzf

arch_home_directories:
  - .config
  - .local/bin
  - .local/share
  - .local/state
