---
gui_enable: true

gui_core_packages:
  - wayland
  - xorg-xwayland
  - wl-clipboard
  - xdg-desktop-portal
  - xdg-desktop-portal-hyprland
  - pipewire
  - pipewire-pulse
  - wireplumber
  - alacritty

gui_fonts:
  - noto-fonts
  - noto-fonts-emoji

gui_aur_fonts:
  - ttf-jetbrains-mono-nerd

gui_hyprland_packages:
  - hyprland
  - waybar
  - wofi
  - nemo
  - hyprpaper
  - swaync
  - hyprsunset
  - hyprpolkitagent

gui_aur_packages:
  - uwsm
  - waypaper
  - hyprlock
  - hyprshot
  - wallust
  - google-chrome

gui_user_systemd_units:
  - waybar.service
  - swaync.service
  - hyprpaper.service
  - hyprsunset.service
  - hyprpolkitagent.service

wallpapers_dir: "{{ ansible_facts['env'].HOME }}/Pictures/wallpapers"
default_wallpaper: "{{ wallpapers_dir }}/abstract-blocks.jpg"
